language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dpimpinella/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dpimpinella/react-test npm test

after_success:
  - docker build -t dpimpinella/multi-client ./client
  - docker build -t dpimpinella/multi-nginx ./nginx
  - docker build -t dpimpinella/multi-server ./server
  - docker build -t dpimpinella/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dpimpinella/multi-client
  - docker push dpimpinella/multi-nginx
  - docker push dpimpinella/multi-server
  - docker push dpimpinella/multi-worker